[release]
# One version for the entire workspace
shared-version = true          # same as the old `workspace = true`
consolidate    = true          # single history/changelog commit
publish        = false         # flip to true when you really want `cargo publish`

# Optional niceties
conventional   = true          # use Conventional Commits for CHANGELOG
tag-name       = "v{{version}}"
tag-message    = "Release {{version}}"
pre-release-commit-message = "chore: (cargo-release) bump to {{version}}"

