# release.toml  – root keys, no table header
shared-version = true          # one version across the workspace
consolidate    = true          # single changelog+tag commit
publish        = false         # set true when you want `cargo publish`

# optional polish
conventional   = true          # Conventional-Commits → CHANGELOG
tag-name       = "v{{version}}"
tag-message    = "Release {{version}}"
pre-release-commit-message = "chore: (cargo-release) bump to {{version}}"

