[package]
name    = "decoder_capstone"
version.workspace = true      # <── this tells Cargo to inherit 0.1.0
edition = "2021"
[dependencies]
decay_core = { path = "../decay_core" }
capstone   = { version = "0.12"}

